<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="28141" started-at="2021-05-30T12:23:20 CST" finished-at="2021-05-30T12:23:48 CST">
    <groups>
    </groups>
    <test name="F:/code/auto_test_framework" duration-ms="28141" started-at="2021-05-30T12:23:20 CST" finished-at="2021-05-30T12:23:48 CST">
      <class name="com.lemon.testcases.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="setup" is-config="true" duration-ms="6648" started-at="2021-05-30T12:23:20 CST" finished-at="2021-05-30T12:23:27 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTestSuccess()[pri:1, instance:com.lemon.testcases.LoginTest@5ae76500]" name="loginTestSuccess" duration-ms="2165" started-at="2021-05-30T12:23:27 CST" finished-at="2021-05-30T12:23:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestSuccess -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="teardown" is-config="true" duration-ms="1066" started-at="2021-05-30T12:23:29 CST" finished-at="2021-05-30T12:23:30 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="setup" is-config="true" duration-ms="3601" started-at="2021-05-30T12:23:30 CST" finished-at="2021-05-30T12:23:34 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTestFailure1()[pri:2, instance:com.lemon.testcases.LoginTest@5ae76500]" name="loginTestFailure1" duration-ms="629" started-at="2021-05-30T12:23:34 CST" finished-at="2021-05-30T12:23:35 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestFailure1 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="teardown" is-config="true" duration-ms="1242" started-at="2021-05-30T12:23:35 CST" finished-at="2021-05-30T12:23:36 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="setup" is-config="true" duration-ms="4028" started-at="2021-05-30T12:23:36 CST" finished-at="2021-05-30T12:23:40 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginTestFailure2(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:com.lemon.testcases.LoginTest@5ae76500]" name="loginTestFailure2" duration-ms="1105" started-at="2021-05-30T12:23:40 CST" data-provider="loginTestFailureDatas" finished-at="2021-05-30T12:23:41 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ab%12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[请输入手机号1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [请输入手机号1] but found [请输入手机号]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [请输入手机号1] but found [请输入手机号]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.lemon.base.Assertion.myAssertEquals(Assertion.java:54)
at com.lemon.testcases.LoginTest.loginTestFailure2(LoginTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at com.lemon.listener.TestFailListener.run(TestFailListener.java:20)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:251)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:580)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestFailure2 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="teardown" is-config="true" duration-ms="1021" started-at="2021-05-30T12:23:41 CST" finished-at="2021-05-30T12:23:42 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="setup" is-config="true" duration-ms="3775" started-at="2021-05-30T12:23:42 CST" finished-at="2021-05-30T12:23:46 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginTestFailure2(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:com.lemon.testcases.LoginTest@5ae76500]" name="loginTestFailure2" duration-ms="1261" started-at="2021-05-30T12:23:46 CST" data-provider="loginTestFailureDatas" finished-at="2021-05-30T12:23:47 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[1585901925]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ab%12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[请输入正确的手机号1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [请输入正确的手机号1] but found [请输入正确的手机号]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [请输入正确的手机号1] but found [请输入正确的手机号]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.lemon.base.Assertion.myAssertEquals(Assertion.java:54)
at com.lemon.testcases.LoginTest.loginTestFailure2(LoginTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at com.lemon.listener.TestFailListener.run(TestFailListener.java:20)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:251)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:580)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestFailure2 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.lemon.testcases.LoginTest@5ae76500]" name="teardown" is-config="true" duration-ms="1045" started-at="2021-05-30T12:23:47 CST" finished-at="2021-05-30T12:23:48 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.lemon.testcases.LoginTest -->
    </test> <!-- F:/code/auto_test_framework -->
  </suite> <!-- All Test Suite -->
</testng-results>
